#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QVariant>
#include <QAction>
#include <QApplication>
#include <QButtonGroup>
#include <QFrame>
#include <QGroupBox>
#include <QLabel>
#include <QMainWindow>
#include <QProgressBar>
#include <QPushButton>

class Ui_MainWindow
{
public:
    QFrame *centralwidget;
    QFrame *frame_Dialpad;
    QPushButton *pushButton_Number_4;
    QPushButton *pushButton_Number_5;
    QPushButton *pushButton_Number_7;
    QPushButton *pushButton_Number_8;
    QPushButton *pushButton_Number_0;
    QPushButton *pushButton_Number_Pound;
    QPushButton *pushButton_Number_2;
    QPushButton *pushButton_Number_1;
    QPushButton *pushButton_Number_3;
    QPushButton *pushButton_Number_6;
    QPushButton *pushButton_Number_9;
    QPushButton *pushButton_Number_Star;
    QPushButton *pushButton_Settings;
    QLabel *label_Yakaphone;
    QProgressBar *progressBar_Mocrophone;
    QLabel *label_MicrophoneLabel_2;
    QProgressBar *progressBar_Loudspeaker;
    QLabel *label_MicrophoneLabel;
    QPushButton *pushButton_Minimize;
    QPushButton *pushButton_DialAnsDrop;
    QPushButton *pushButton_HoldResume;
    QPushButton *pushButton_Credit;
    QPushButton *pushButton_Close;
    QGroupBox *groupBox_Display;
    QLabel *label;
    QFrame *line_2;
    QFrame *line;
    QLabel *label_StatusCaption;
    QLabel *label_StatusText;
    QPushButton *pushButton_CallRecord_Backward;
    QPushButton *pushButton_CallRecord_Forward;
    QLabel *label_TelNumber;
    QLabel *label_TimerCaption;
    QLabel *label_TimerText;

    void setupUi(QMainWindow *MainWindow)
    {
    MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
    MainWindow->setEnabled(true);
    MainWindow->resize(QSize(260, 400).expandedTo(MainWindow->minimumSizeHint()));
    QSizePolicy sizePolicy(static_cast<QSizePolicy::Policy>(0), static_cast<QSizePolicy::Policy>(0));
    sizePolicy.setHorizontalStretch(44);
    sizePolicy.setVerticalStretch(200);
    sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
    MainWindow->setSizePolicy(sizePolicy);
    MainWindow->setMinimumSize(QSize(260, 400));
    MainWindow->setMaximumSize(QSize(260, 390));
    MainWindow->setWindowIcon(QIcon(QString::fromUtf8(":/application/logoicon16x16.png")));
    MainWindow->setIconSize(QSize(16, 16));
    MainWindow->setToolButtonStyle(Qt::ToolButtonTextBesideIcon);
    centralwidget = new QFrame(MainWindow);
    centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
    centralwidget->setMinimumSize(QSize(260, 380));
    centralwidget->setBaseSize(QSize(260, 380));
    frame_Dialpad = new QFrame(centralwidget);
    frame_Dialpad->setObjectName(QString::fromUtf8("frame_Dialpad"));
    frame_Dialpad->setGeometry(QRect(10, 230, 118, 148));
    frame_Dialpad->setFrameShape(QFrame::StyledPanel);
    frame_Dialpad->setFrameShadow(QFrame::Raised);
    pushButton_Number_4 = new QPushButton(frame_Dialpad);
    pushButton_Number_4->setObjectName(QString::fromUtf8("pushButton_Number_4"));
    pushButton_Number_4->setGeometry(QRect(0, 36, 32, 32));
    pushButton_Number_4->setIcon(QIcon(QString::fromUtf8(":/numberPad/4_a.png")));
    pushButton_Number_4->setIconSize(QSize(32, 32));
    pushButton_Number_5 = new QPushButton(frame_Dialpad);
    pushButton_Number_5->setObjectName(QString::fromUtf8("pushButton_Number_5"));
    pushButton_Number_5->setGeometry(QRect(40, 36, 32, 32));
    pushButton_Number_5->setIcon(QIcon(QString::fromUtf8(":/numberPad/5_a.png")));
    pushButton_Number_5->setIconSize(QSize(32, 32));
    pushButton_Number_7 = new QPushButton(frame_Dialpad);
    pushButton_Number_7->setObjectName(QString::fromUtf8("pushButton_Number_7"));
    pushButton_Number_7->setGeometry(QRect(0, 72, 32, 32));
    pushButton_Number_7->setIcon(QIcon(QString::fromUtf8(":/numberPad/7_a.png")));
    pushButton_Number_7->setIconSize(QSize(32, 32));
    pushButton_Number_8 = new QPushButton(frame_Dialpad);
    pushButton_Number_8->setObjectName(QString::fromUtf8("pushButton_Number_8"));
    pushButton_Number_8->setGeometry(QRect(40, 72, 32, 32));
    pushButton_Number_8->setIcon(QIcon(QString::fromUtf8(":/numberPad/8_a.png")));
    pushButton_Number_8->setIconSize(QSize(32, 32));
    pushButton_Number_0 = new QPushButton(frame_Dialpad);
    pushButton_Number_0->setObjectName(QString::fromUtf8("pushButton_Number_0"));
    pushButton_Number_0->setGeometry(QRect(40, 108, 32, 32));
    pushButton_Number_0->setIcon(QIcon(QString::fromUtf8(":/numberPad/0_a.png")));
    pushButton_Number_0->setIconSize(QSize(32, 32));
    pushButton_Number_Pound = new QPushButton(frame_Dialpad);
    pushButton_Number_Pound->setObjectName(QString::fromUtf8("pushButton_Number_Pound"));
    pushButton_Number_Pound->setGeometry(QRect(80, 108, 32, 32));
    pushButton_Number_Pound->setIcon(QIcon(QString::fromUtf8(":/numberPad/raute_a.png")));
    pushButton_Number_Pound->setIconSize(QSize(32, 32));
    pushButton_Number_2 = new QPushButton(frame_Dialpad);
    pushButton_Number_2->setObjectName(QString::fromUtf8("pushButton_Number_2"));
    pushButton_Number_2->setGeometry(QRect(40, 0, 32, 32));
    pushButton_Number_2->setIcon(QIcon(QString::fromUtf8(":/numberPad/2_a.png")));
    pushButton_Number_2->setIconSize(QSize(32, 32));
    pushButton_Number_1 = new QPushButton(frame_Dialpad);
    pushButton_Number_1->setObjectName(QString::fromUtf8("pushButton_Number_1"));
    pushButton_Number_1->setGeometry(QRect(0, 0, 32, 32));
    pushButton_Number_1->setIcon(QIcon(QString::fromUtf8(":/numberPad/1_a.png")));
    pushButton_Number_1->setIconSize(QSize(32, 32));
    pushButton_Number_1->setAutoRepeat(false);
    pushButton_Number_1->setFlat(false);
    pushButton_Number_3 = new QPushButton(frame_Dialpad);
    pushButton_Number_3->setObjectName(QString::fromUtf8("pushButton_Number_3"));
    pushButton_Number_3->setGeometry(QRect(80, 0, 32, 32));
    pushButton_Number_3->setIcon(QIcon(QString::fromUtf8(":/numberPad/3_a.png")));
    pushButton_Number_3->setIconSize(QSize(32, 32));
    pushButton_Number_6 = new QPushButton(frame_Dialpad);
    pushButton_Number_6->setObjectName(QString::fromUtf8("pushButton_Number_6"));
    pushButton_Number_6->setGeometry(QRect(80, 36, 32, 32));
    pushButton_Number_6->setIcon(QIcon(QString::fromUtf8(":/numberPad/6_a.png")));
    pushButton_Number_6->setIconSize(QSize(32, 32));
    pushButton_Number_9 = new QPushButton(frame_Dialpad);
    pushButton_Number_9->setObjectName(QString::fromUtf8("pushButton_Number_9"));
    pushButton_Number_9->setGeometry(QRect(80, 72, 32, 32));
    pushButton_Number_9->setIcon(QIcon(QString::fromUtf8(":/numberPad/9_a.png")));
    pushButton_Number_9->setIconSize(QSize(32, 32));
    pushButton_Number_Star = new QPushButton(frame_Dialpad);
    pushButton_Number_Star->setObjectName(QString::fromUtf8("pushButton_Number_Star"));
    pushButton_Number_Star->setGeometry(QRect(0, 108, 32, 32));
    pushButton_Number_Star->setIcon(QIcon(QString::fromUtf8(":/numberPad/__a.png")));
    pushButton_Number_Star->setIconSize(QSize(32, 32));
    pushButton_Settings = new QPushButton(centralwidget);
    pushButton_Settings->setObjectName(QString::fromUtf8("pushButton_Settings"));
    pushButton_Settings->setGeometry(QRect(150, 354, 100, 16));
    pushButton_Settings->setIcon(QIcon(QString::fromUtf8(":/controlPad/Settings_a.png")));
    pushButton_Settings->setIconSize(QSize(100, 32));
    label_Yakaphone = new QLabel(centralwidget);
    label_Yakaphone->setObjectName(QString::fromUtf8("label_Yakaphone"));
    label_Yakaphone->setGeometry(QRect(10, 6, 201, 20));
    QFont font;
    font.setFamily(QString::fromUtf8("MS Shell Dlg"));
    font.setPointSize(10);
    font.setBold(true);
    font.setItalic(false);
    font.setUnderline(false);
    font.setWeight(75);
    font.setStrikeOut(false);
    label_Yakaphone->setFont(font);
    label_Yakaphone->setAlignment(Qt::AlignCenter);
    progressBar_Mocrophone = new QProgressBar(centralwidget);
    progressBar_Mocrophone->setObjectName(QString::fromUtf8("progressBar_Mocrophone"));
    progressBar_Mocrophone->setGeometry(QRect(10, 206, 100, 16));
    progressBar_Mocrophone->setLayoutDirection(Qt::RightToLeft);
    progressBar_Mocrophone->setValue(50);
    progressBar_Mocrophone->setTextVisible(true);
    progressBar_Mocrophone->setOrientation(Qt::Horizontal);
    label_MicrophoneLabel_2 = new QLabel(centralwidget);
    label_MicrophoneLabel_2->setObjectName(QString::fromUtf8("label_MicrophoneLabel_2"));
    label_MicrophoneLabel_2->setGeometry(QRect(134, 210, 14, 12));
    label_MicrophoneLabel_2->setPixmap(QPixmap(QString::fromUtf8(":/application/loudpeaker.png")));
    progressBar_Loudspeaker = new QProgressBar(centralwidget);
    progressBar_Loudspeaker->setObjectName(QString::fromUtf8("progressBar_Loudspeaker"));
    progressBar_Loudspeaker->setGeometry(QRect(150, 206, 100, 16));
    progressBar_Loudspeaker->setValue(50);
    progressBar_Loudspeaker->setTextVisible(true);
    progressBar_Loudspeaker->setOrientation(Qt::Horizontal);
    label_MicrophoneLabel = new QLabel(centralwidget);
    label_MicrophoneLabel->setObjectName(QString::fromUtf8("label_MicrophoneLabel"));
    label_MicrophoneLabel->setGeometry(QRect(110, 210, 14, 12));
    label_MicrophoneLabel->setPixmap(QPixmap(QString::fromUtf8(":/application/microphone.png")));
    pushButton_Minimize = new QPushButton(centralwidget);
    pushButton_Minimize->setObjectName(QString::fromUtf8("pushButton_Minimize"));
    pushButton_Minimize->setGeometry(QRect(216, 8, 15, 15));
    pushButton_Minimize->setIcon(QIcon(QString::fromUtf8(":/application/WindowMinimize.png")));
    pushButton_Minimize->setIconSize(QSize(15, 15));
    pushButton_DialAnsDrop = new QPushButton(centralwidget);
    pushButton_DialAnsDrop->setObjectName(QString::fromUtf8("pushButton_DialAnsDrop"));
    pushButton_DialAnsDrop->setEnabled(false);
    pushButton_DialAnsDrop->setGeometry(QRect(150, 230, 100, 32));
    pushButton_DialAnsDrop->setIcon(QIcon(QString::fromUtf8(":/controlPad/Dial_a.png")));
    pushButton_DialAnsDrop->setIconSize(QSize(100, 32));
    pushButton_HoldResume = new QPushButton(centralwidget);
    pushButton_HoldResume->setObjectName(QString::fromUtf8("pushButton_HoldResume"));
    pushButton_HoldResume->setEnabled(false);
    pushButton_HoldResume->setGeometry(QRect(150, 266, 100, 32));
    pushButton_HoldResume->setIcon(QIcon(QString::fromUtf8(":/controlPad/Hold_a.png")));
    pushButton_HoldResume->setIconSize(QSize(100, 32));
    pushButton_Credit = new QPushButton(centralwidget);
    pushButton_Credit->setObjectName(QString::fromUtf8("pushButton_Credit"));
    pushButton_Credit->setEnabled(false);
    pushButton_Credit->setGeometry(QRect(150, 302, 100, 32));
    pushButton_Credit->setIcon(QIcon(QString::fromUtf8(":/controlPad/Credit_a.png")));
    pushButton_Credit->setIconSize(QSize(100, 32));
    pushButton_Close = new QPushButton(centralwidget);
    pushButton_Close->setObjectName(QString::fromUtf8("pushButton_Close"));
    pushButton_Close->setGeometry(QRect(234, 8, 15, 15));
    pushButton_Close->setIcon(QIcon(QString::fromUtf8(":/application/WindowClose.png")));
    pushButton_Close->setIconSize(QSize(15, 15));
    groupBox_Display = new QGroupBox(centralwidget);
    groupBox_Display->setObjectName(QString::fromUtf8("groupBox_Display"));
    groupBox_Display->setGeometry(QRect(10, 30, 241, 161));
    label = new QLabel(groupBox_Display);
    label->setObjectName(QString::fromUtf8("label"));
    label->setGeometry(QRect(190, 0, 49, 42));
    label->setFrameShape(QFrame::NoFrame);
    label->setPixmap(QPixmap(QString::fromUtf8(":/application/logo.png")));
    line_2 = new QFrame(groupBox_Display);
    line_2->setObjectName(QString::fromUtf8("line_2"));
    line_2->setGeometry(QRect(10, 125, 221, 16));
    line_2->setFrameShape(QFrame::HLine);
    line = new QFrame(groupBox_Display);
    line->setObjectName(QString::fromUtf8("line"));
    line->setGeometry(QRect(10, 20, 181, 16));
    line->setFrameShape(QFrame::HLine);
    label_StatusCaption = new QLabel(groupBox_Display);
    label_StatusCaption->setObjectName(QString::fromUtf8("label_StatusCaption"));
    label_StatusCaption->setGeometry(QRect(10, 10, 40, 14));
    QFont font1;
    font1.setFamily(QString::fromUtf8("MS Shell Dlg"));
    font1.setPointSize(8);
    font1.setBold(true);
    font1.setItalic(false);
    font1.setUnderline(false);
    font1.setWeight(75);
    font1.setStrikeOut(false);
    label_StatusCaption->setFont(font1);
    label_StatusText = new QLabel(groupBox_Display);
    label_StatusText->setObjectName(QString::fromUtf8("label_StatusText"));
    label_StatusText->setGeometry(QRect(52, 9, 140, 16));
    QFont font2;
    font2.setFamily(QString::fromUtf8("MS Shell Dlg"));
    font2.setPointSize(8);
    font2.setBold(false);
    font2.setItalic(false);
    font2.setUnderline(false);
    font2.setWeight(50);
    font2.setStrikeOut(false);
    label_StatusText->setFont(font2);
    pushButton_CallRecord_Backward = new QPushButton(groupBox_Display);
    pushButton_CallRecord_Backward->setObjectName(QString::fromUtf8("pushButton_CallRecord_Backward"));
    pushButton_CallRecord_Backward->setGeometry(QRect(167, 138, 30, 15));
    pushButton_CallRecord_Backward->setIcon(QIcon(QString::fromUtf8(":/application/callRecordBackward.png")));
    pushButton_CallRecord_Backward->setIconSize(QSize(15, 15));
    pushButton_CallRecord_Forward = new QPushButton(groupBox_Display);
    pushButton_CallRecord_Forward->setObjectName(QString::fromUtf8("pushButton_CallRecord_Forward"));
    pushButton_CallRecord_Forward->setGeometry(QRect(201, 138, 30, 15));
    pushButton_CallRecord_Forward->setIcon(QIcon(QString::fromUtf8(":/application/callRecordFoward.png")));
    pushButton_CallRecord_Forward->setIconSize(QSize(30, 15));
    label_TelNumber = new QLabel(groupBox_Display);
    label_TelNumber->setObjectName(QString::fromUtf8("label_TelNumber"));
    label_TelNumber->setGeometry(QRect(10, 100, 221, 25));
    QFont font3;
    font3.setFamily(QString::fromUtf8("Elephant"));
    font3.setPointSize(12);
    font3.setBold(true);
    font3.setItalic(false);
    font3.setUnderline(false);
    font3.setWeight(75);
    font3.setStrikeOut(false);
    label_TelNumber->setFont(font3);
    label_TelNumber->setAutoFillBackground(false);
    label_TelNumber->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_TimerCaption = new QLabel(groupBox_Display);
    label_TimerCaption->setObjectName(QString::fromUtf8("label_TimerCaption"));
    label_TimerCaption->setGeometry(QRect(10, 141, 47, 14));
    QFont font4;
    font4.setFamily(QString::fromUtf8("MS Shell Dlg"));
    font4.setPointSize(8);
    font4.setBold(true);
    font4.setItalic(false);
    font4.setUnderline(false);
    font4.setWeight(75);
    font4.setStrikeOut(false);
    label_TimerCaption->setFont(font4);
    label_TimerText = new QLabel(groupBox_Display);
    label_TimerText->setObjectName(QString::fromUtf8("label_TimerText"));
    label_TimerText->setGeometry(QRect(50, 140, 111, 16));
    QFont font5;
    font5.setFamily(QString::fromUtf8("MS Shell Dlg"));
    font5.setPointSize(8);
    font5.setBold(false);
    font5.setItalic(false);
    font5.setUnderline(false);
    font5.setWeight(50);
    font5.setStrikeOut(false);
    label_TimerText->setFont(font5);
    retranslateUi(MainWindow);

    QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
    MainWindow->setWindowTitle(QApplication::translate("MainWindow", "YakaPhone", 0));
    pushButton_Number_4->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_Number_5->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_Number_7->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_Number_8->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_Number_0->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_Number_Pound->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_Number_2->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_Number_1->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_Number_3->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_Number_6->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_Number_9->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_Number_Star->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_Settings->setText(QApplication::translate("MainWindow", "", 0));
    label_Yakaphone->setText(QApplication::translate("MainWindow", "      YakaPhone", 0));
    label_MicrophoneLabel_2->setText(QApplication::translate("MainWindow", "", 0));
    label_MicrophoneLabel->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_Minimize->setToolTip(QApplication::translate("MainWindow", "minimize", 0));
    pushButton_Minimize->setWhatsThis(QApplication::translate("MainWindow", "", 0));
    pushButton_Minimize->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_DialAnsDrop->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_HoldResume->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_Credit->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_Close->setToolTip(QApplication::translate("MainWindow", "exit", 0));
    pushButton_Close->setWhatsThis(QApplication::translate("MainWindow", "", 0));
    pushButton_Close->setText(QApplication::translate("MainWindow", "", 0));
    groupBox_Display->setTitle(QApplication::translate("MainWindow", "", 0));
    label->setText(QApplication::translate("MainWindow", "", 0));
    label_StatusCaption->setText(QApplication::translate("MainWindow", "State:", 0));
    label_StatusText->setText(QApplication::translate("MainWindow", "Unknown", 0));
    pushButton_CallRecord_Backward->setText(QApplication::translate("MainWindow", "", 0));
    pushButton_CallRecord_Forward->setText(QApplication::translate("MainWindow", "", 0));
    label_TelNumber->setText(QApplication::translate("MainWindow", "Tel. Nr.", 0));
    label_TimerCaption->setText(QApplication::translate("MainWindow", "Timer:", 0));
    label_TimerText->setText(QApplication::translate("MainWindow", "00:00:00", 0));
    Q_UNUSED(MainWindow);
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

#endif // UI_MAINWINDOW_H
